services:
  server:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_ADDRESS=http://jaeger:14268/api/traces
    depends_on:
      consul:
        condition: service_healthy
      jaeger:
        condition: service_started

  consul:
    image: hashicorp/consul:1.21
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - consul_store:/consul/data
    healthcheck:
      test: ["CMD", "consul", "info"]
      interval: 5s
      timeout: 3s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"

volumes:
  consul_store:
  prometheus-data:
